### ISSUE TITLE
Ability to translate conjunction word "and" to different language

### ISSUE THREAD

**Issue by arzzen** [kontentino/array-semantic-join#13]
https://github.com/kontentino/array-semantic-join/blob/8b22210d795bd55508eb87a7fb6c37165d29f6c8/index.js#L15

**Comment by filippofilip95** [comment]
Hello @arzzen thanks for opening the issue :)  

I'v created PR here #14. 

Basically I added option to pass `word` which is then used in conjunction. 

This should allow to be used this function in different languages.

**Comment by filippofilip95** [comment]
Package has been released. 

Please use version [2.0.1](https://github.com/kontentino/array-semantic-join/releases/tag/v.2.0.1) 

Closing this PR as resolved.
